/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class extern_java_Bindings */

#ifndef _Included_extern_java_Bindings
#define _Included_extern_java_Bindings
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     extern_java_Bindings
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_extern_java_Bindings_hello
  (JNIEnv *, jclass);

/*
 * Class:     extern_java_Bindings
 * Method:    hello2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_extern_java_Bindings_hello2
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
